-- This script creates the database hbtn_0d_usa and table states
-- states values: id INT (unique, autogenerated, can't be null, primary key), name VARCHAR(256) NOT NULL
-- If the database already exists, no error will occur
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE),
    name VARCHAR(256) NOT NULL
);